services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: afds_nest_starter
      POSTGRES_USER: afds
      POSTGRES_PASSWORD: afds
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U afds -d afds_nest_starter']
      interval: 2s
      timeout: 5s
      retries: 10
    volumes:
      - postgres-data:/var/lib/postgresql

volumes:
  postgres-data:
